#include "video.h"

void put_pixel(int x,int y,uint32_t color){
    if(x >= 0 && x <SCREEN_WIDTH && y >=0 && y <SCREEN_HEIGHT){
        VESA_BUFFER[y*SCREEN_WIDTH +x ]=color;
    }
}

/* Copy the code and data in the realmode section down into the lower
 * 64kb of memory @ 0x00001000. */
void realmode_setup (void)
{
    /* Each of these __realmode* values is generated by the linker script */
    uint32_t *src_addr = (uint32_t *)&__realmode_lma_start;
    uint32_t *dst_addr = (uint32_t *)&__realmode_vma_start;
    uint32_t *src_end  = (uint32_t *)&__realmode_lma_end;

    /* Copy a DWORD at a time from source to destination */
    while (src_addr < src_end)
        *dst_addr++ = *src_addr++;
}

void init_font(){
    font =font_bitmap;//指向数据
    
}

//以下针对的是8*16的bitmap fond
void drawchar(unsigned char c ,int x,int y,int fgcolor,int bgcolor){
    int cx,cy;
    int mask[8] ={1,2,4,8,16,32,64,128};
    unsigned char *glyph = font+(int)c*16;

    for(cy=0;cy<16;cy++){
        for(cx=0;cx<8;cx++){
            put_pixel(x+8-cx,y+cy,glyph[cy]&mask[cx]?fgcolor:bgcolor);
        }
    }

}

void drawstring(char* input,int Xray_start,int Yray_start,int fgcolor,int bgcolor){
    size_t len = 0;
    int x=Xray_start;
    int y=Yray_start;
    while ((input[len]))
    {
        if(input[len]=='\n'){ //如果遇到\n，则进行换行
            y=y+CHAR_HEIGHT;
            x=Xray_start;
            len++;
            continue;
        }
            
        drawchar(input[len],x,y,fgcolor,bgcolor);
        x=x+CHAR_WIDTH;
        if(x == SCREEN_WIDTH){
            x=Xray_start;
            y=y+CHAR_HEIGHT;
            if(y==SCREEN_HEIGHT){
                y=Yray_start;
            }
        }
        len++;
    }

}
void video_init(){
    struct mode_info_t *pMI;
    struct multiboot_info *mb_info;
    const uint32_t magicnum;
    /* Quiet compiler about unused variables */
    (void) mb_info;
    (void) magicnum;

    /* Setup the GDT */
    gdt_setup(gdt, NUM_GDT_ENTRIES);

    /* Setup real mode code and data */
    realmode_setup();

    /* Switch to video mode 0x13 (320x200x256)
     * The physical address of the mode 13 video memory is
     * 0xa0000 */
    pMI = do_vbe(0x13);
    video_gfx_ptr = pMI->physbase;
    init_font();
}